export enum EAdminNavigation {
  dashboard = '/admin/dashboard',
  authLogin = '/admin/auth/login',
  authLogout = '/admin/auth/logout',
  users = '/admin/users',
  usersCreate = '/admin/users/new',
  userChangeLanguage = '/admin',
  customers = '/admin/customers',
  customersCreate = '/admin/customers/new',
  categories = '/admin/categories',
  categoriesCreate = '/admin/categories/new',
  products = '/admin/products',
  productsCreate = '/admin/products/new',
  reviews = '/admin/reviews',
  reviewsCreate = '/admin/reviews/new',
  orders = '/admin/orders',
  carts = '/admin/carts',
  apiCategories = '/admin/api/categories',
  apiCustomers = '/admin/api/customers',
  apiProducts = '/admin/api/products',
  unauthorized = '/admin/unauthorized'
}
